In [2]:
import numpy as np 

## DataTypes & Attributes

In [3]:
#NumPy's Main datatype is ndarray
a1 = np.array([1, 2, 3])

In [4]:
a2 = np.array([[1, 2.0, 3.3] ,
             [4, 5, 6.5]])


a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])


In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.shape

(3, 2, 3)

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('float64')

In [12]:
a3.dtype

dtype('int32')

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#Create a dataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros([2, 3])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 4, 8, 0, 4],
       [3, 9, 9, 8, 9],
       [6, 1, 7, 3, 3]])

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array.size

15

In [28]:
random_array_2 = np.random.random((5, 3))
random_array_2
random_array_2.shape

(5, 3)

In [45]:
#Pseudo - random numbers
np.random.seed(seed = 9999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [35]:
random_array_4.shape


(5, 3)

In [33]:
random_array_4.size

15

In [56]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

#3. Viewing arrays and matrices 

In [57]:
random_array_4.unique

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [58]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [59]:
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [60]:
a1 

array([1, 2, 3])

In [61]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [63]:
a1[0]

1

In [64]:
a2[0]

array([1. , 2. , 3.3])

In [65]:
a2.shape

(2, 3)

In [66]:
a3.shape

(3, 2, 3)

In [67]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [69]:
a2[1]



array([4. , 5. , 6.5])

In [70]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [71]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [72]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [73]:
a4.shape

(2, 3, 4, 5)

In [74]:
a4.ndim

4

In [86]:
a4[0][2][0], a4[:, :, :, :3]

(array([4, 3, 1, 9, 5]),
 array([[[[3, 5, 8],
          [5, 0, 0],
          [9, 6, 4],
          [3, 3, 8]],
 
         [[1, 0, 0],
          [7, 9, 3],
          [7, 7, 0],
          [3, 1, 3]],
 
         [[4, 3, 1],
          [9, 1, 2],
          [2, 5, 7],
          [9, 9, 3]]],
 
 
        [[[3, 0, 4],
          [7, 2, 7],
          [6, 6, 5],
          [7, 1, 5]],
 
         [[9, 9, 0],
          [6, 8, 2],
          [6, 1, 5],
          [9, 8, 6]],
 
         [[7, 5, 4],
          [8, 1, 5],
          [3, 7, 7],
          [7, 5, 9]]]]))

## 4. Manipulating & comparing arrays

## Arithmentic 

In [81]:
a1

array([1, 2, 3])

In [82]:
ones = np.ones(3)

In [83]:
ones

array([1., 1., 1.])

In [84]:
a1 +ones

array([2., 3., 4.])

In [87]:
a1 - ones

array([0., 1., 2.])

In [88]:
a1 * ones

array([1., 2., 3.])

In [89]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [90]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [91]:
a3 * a2

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [92]:
a3, a2

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [93]:
a2* a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [94]:
# reshaping numpy arrays
a1 / ones

array([1., 2., 3.])

In [95]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [98]:
# Floor division removes the decimals and rounds down
a2 // a1 

array([[1., 1., 1.],
       [4., 2., 2.]])

In [99]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [100]:
3.3 * 3.3 

10.889999999999999

In [101]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [102]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [103]:
np.add(a1, ones)

array([2., 3., 4.])

In [104]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [105]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [106]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [107]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [108]:
2.71 ** 2

7.3441

In [109]:
2.71 ** 3

19.902511

## Aggregation 

Aggregation = performing the same operation on a number of things

In [111]:
List = [1, 2,3]

In [112]:
type(list)

type

In [113]:
sum(list)

TypeError: 'type' object is not iterable

In [114]:
type(List)

list

In [115]:
sum(Type)

NameError: name 'Type' is not defined

In [116]:
sum(List)

6

Use Python's methods (`sum()`) on Python datatypes and NumPy's methods on NumPy arrays (`np.sum()`)

In [117]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [118]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [119]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's sum method np.sum()

6.33 ms ± 415 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.3 µs ± 64.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [120]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [121]:
np.mean(a2)

3.6333333333333333

In [122]:
np.max(a2)

6.5

In [123]:
np.std(a2)

1.8226964152656422

In [124]:
# Variance = measure of average degree to which each number is different 
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224